[package]
name = "governor"
version = "0.1.0"
authors = ["Adityo Pratomo <pratomo.adityo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
serde_json = "1.0"
serde_yaml = "0.8.7"
